import config
from generator.design.design_generator import DesignGenerator
from generator.design.core.frame_generator import FrameGenerator


class ScriptGenerator(DesignGenerator):

    def generate_design(self):
        yield from f"""try:
    import {config.gui_controller_file_name.split('.')[0]} as GuiController    
except Exception as e:
    print("Exception while importing gui_controller.py")
    print(e)
try : 
    import {config.gui_handler_file_name.split('.')[0]} as GuiHandler
except Exception as e:
    print("Exception while importing gui_handler.py")
    print(e)    
from PySide6.QtSvgWidgets import QSvgWidget
from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform, QPen, QPainterPath)
from PySide6.QtWidgets import (QApplication, QFrame, QHeaderView, QLabel,
    QLineEdit, QMainWindow, QPushButton, QSizePolicy,
    QStatusBar, QTableView, QWidget)""".splitlines()
        figma_frames = self.figma_node['children']
        frames = []
        for frame in figma_frames:
            frame = FrameGenerator(frame, self)
            frames.append(frame)
            yield from frame.generate_design()
        yield from """import sys

app = QApplication(sys.argv)""".splitlines()
        for frame in frames:
            yield from f"""MainWindow = QMainWindow()
ui = {frame.window_class_name}()
ui.setupUi(MainWindow)
MainWindow.show()
app.exec()""".splitlines()

    def generate_handler(self):
        yield from f"""\"\"\"
This file was generated by PyQT figma designer
You can edit it but be careful to not overwrite it afterwards.
Each function is connected to a specific event of a specific widget in the GUI.
\"\"\"

# imports
from PySide6.QtCore import *
from PySide6.QtGui import *
from PySide6.QtWidgets import *
from gui_controller import *
""".splitlines()
        yield from super().generate_handler()

    def generate_controller(self):
        yield from f"""\"\"\"
This file was generated by PyQT figma designer
DO NOT EDIT IT. It could cause errors and it is not the way to use this program.
You can call functions from this file in your own code. 
It will allow you to change the GUI from your own code.
\"\"\"

# imports
from PySide6.QtCore import *
from PySide6.QtGui import *
from PySide6.QtWidgets import *
""".splitlines()
        yield from super().generate_controller()
