"""
This file was generated by PyQT figma designer
You can edit it but be careful to not overwrite it afterwards.
Each function is connected to a specific event of a specific widget in the GUI.
"""

# imports
from PySide6.QtCore import *
from PySide6.QtGui import *
from PySide6.QtWidgets import *
from gui_controller import *


class ComponentsPackHandler:

    @classmethod
    def window_started(cls):
        pass
        
    @classmethod
    def window_closed(cls):
        pass
    @classmethod
    def button_1_1_clicked(cls) : 
        print("Button button_1_1 clicked")
    @classmethod
    def custom_button_1_1_clicked(cls):
        print("CustomButton custom_button_1_1 clicked")
    @classmethod
    def checkbox_1_check_changed(cls, checked:bool) :
        print("Checkbox checkbox_1 checked = " + str(checked))
    class GroupSlider0Handler:
        
        @classmethod
        def slider_1_1_value_changed(cls, value:float) :
            print("Slider slider_1_1 value changed = " + str(value))
    class GroupCustomTextField0Handler:
        
        @classmethod
        def custom_text_field_1_1_text_changed(cls, text:str) :
            print("Text field custom_text_field_1_1_text_changed text changed to text : " + text)
    class GroupTextfield0Handler:
        
        @classmethod
        def text_field_1_2_text_changed(cls, text:str) :
            print("Text field text_field_1_2_text_changed text changed to text : " + text)
    class GroupTabsView0Handler:
        
        @classmethod
        def tabs_view_1_tab_changed(cls, tab:int) :
            print("Tabs view tabs_view_1 tab changed to tab : " + str(tab))