"""
This file was generated by PyQT figma designer
DO NOT EDIT IT. It could cause errors and it is not the way to use this program.
You can call functions from this file in your own code. 
It will allow you to change the GUI from your own code.
"""

# imports
from PySide6.QtCore import *
from PySide6.QtGui import *
from PySide6.QtWidgets import *
class PyqtFigmaDesignerGuiV4Controller:
    class PyqtFigmaDesignerGuiV42Controller:
        class GroupTitle0Controller:
            
            @classmethod
            def text_0_set_text(cls, text:str):
                print("The function text_0_set_text is unfortunately not linked to the controller")
        class TabsView0Controller:
            class Background2Controller:
                class TabDownload0Controller:
                    class TabUnchecked1Controller:
                        
                        @classmethod
                        def label_0_set_text(cls, text:str):
                            print("The function label_0_set_text is unfortunately not linked to the controller")
                class TabRun0Controller:
                    class TabUnchecked4Controller:
                        
                        @classmethod
                        def label_2_set_text(cls, text:str):
                            print("The function label_2_set_text is unfortunately not linked to the controller")
                class TabCompile0Controller:
                    class TabUnchecked7Controller:
                        
                        @classmethod
                        def label_4_set_text(cls, text:str):
                            print("The function label_4_set_text is unfortunately not linked to the controller")
                class TabCreateProject0Controller:
                    class TabUnchecked10Controller:
                        
                        @classmethod
                        def label_6_set_text(cls, text:str):
                            print("The function label_6_set_text is unfortunately not linked to the controller")
            class TabsContent0Controller:
                class Run0Controller:
                    class CustomButtonRun0Controller:
                        class Normal1Controller:
                            
                            @classmethod
                            def text_2_set_text(cls, text:str):
                                print("The function text_2_set_text is unfortunately not linked to the controller")
                        class Disabled1Controller:
                            
                            @classmethod
                            def text_4_set_text(cls, text:str):
                                print("The function text_4_set_text is unfortunately not linked to the controller")
                        class Pressed1Controller:
                            
                            @classmethod
                            def text_6_set_text(cls, text:str):
                                print("The function text_6_set_text is unfortunately not linked to the controller")
                        class MouseOver1Controller:
                            
                            @classmethod
                            def text_8_set_text(cls, text:str):
                                print("The function text_8_set_text is unfortunately not linked to the controller")
                    
                    @classmethod
                    def custom_button_run_1_enable(cls):
                         print("The function custom_button_run_1_enable is unfortunately not linked to the controller")
                     
                    @classmethod
                    def custom_button_run_1_disable(cls):
                            print("The function custom_button_run_1_disable is unfortunately not linked to the controller")
                class Compile0Controller:
                    class CheckboxOverwriteHandlers0Controller:
                        
                        @classmethod
                        def overwrite_handlers_0_set_text(cls, text:str):
                            print("The function overwrite_handlers_0_set_text is unfortunately not linked to the controller")
                    
                    @classmethod
                    def checkbox_overwrite_handlers_1_set_checked(cls, checked:bool) :
                        print("The function checkbox_overwrite_handlers_1_set_checked is unfortunately not linked to the controller")
                    class CheckboxOverwriteConfig0Controller:
                        
                        @classmethod
                        def overwrite_styles_0_set_text(cls, text:str):
                            print("The function overwrite_styles_0_set_text is unfortunately not linked to the controller")
                    
                    @classmethod
                    def checkbox_overwrite_config_1_set_checked(cls, checked:bool) :
                        print("The function checkbox_overwrite_config_1_set_checked is unfortunately not linked to the controller")
                    class CheckboxOverwriteStrings0Controller:
                        
                        @classmethod
                        def overwrite_strings_0_set_text(cls, text:str):
                            print("The function overwrite_strings_0_set_text is unfortunately not linked to the controller")
                    
                    @classmethod
                    def checkbox_overwrite_strings_1_set_checked(cls, checked:bool) :
                        print("The function checkbox_overwrite_strings_1_set_checked is unfortunately not linked to the controller")
                    class GroupSliderScale0Controller:
                        
                        @classmethod
                        def slider_scale_1_set_value(cls, value:float) :
                            print("The function slider_scale_1_set_value is unfortunately not linked to the controller")
                        
                        @classmethod
                        def scale_0_set_text(cls, text:str):
                            print("The function scale_0_set_text is unfortunately not linked to the controller")
                        
                        @classmethod
                        def x1_0_set_text(cls, text:str):
                            print("The function x1_0_set_text is unfortunately not linked to the controller")
                    class GroupSliderTextScale0Controller:
                        
                        @classmethod
                        def slider_scale_4_set_value(cls, value:float) :
                            print("The function slider_scale_4_set_value is unfortunately not linked to the controller")
                        
                        @classmethod
                        def text_scale_0_set_text(cls, text:str):
                            print("The function text_scale_0_set_text is unfortunately not linked to the controller")
                        
                        @classmethod
                        def x1_2_set_text(cls, text:str):
                            print("The function x1_2_set_text is unfortunately not linked to the controller")
                    class CustomButtonCompile0Controller:
                        class Normal4Controller:
                            
                            @classmethod
                            def text_10_set_text(cls, text:str):
                                print("The function text_10_set_text is unfortunately not linked to the controller")
                        class Disabled4Controller:
                            
                            @classmethod
                            def text_12_set_text(cls, text:str):
                                print("The function text_12_set_text is unfortunately not linked to the controller")
                        class Pressed4Controller:
                            
                            @classmethod
                            def text_14_set_text(cls, text:str):
                                print("The function text_14_set_text is unfortunately not linked to the controller")
                        class MouseOver4Controller:
                            
                            @classmethod
                            def text_16_set_text(cls, text:str):
                                print("The function text_16_set_text is unfortunately not linked to the controller")
                    
                    @classmethod
                    def custom_button_compile_1_enable(cls):
                         print("The function custom_button_compile_1_enable is unfortunately not linked to the controller")
                     
                    @classmethod
                    def custom_button_compile_1_disable(cls):
                            print("The function custom_button_compile_1_disable is unfortunately not linked to the controller")
                class Download0Controller:
                    class GroupTextFieldFigmaToken0Controller:
                        
                        @classmethod
                        def title_0_set_text(cls, text:str):
                            print("The function title_0_set_text is unfortunately not linked to the controller")
                        class CustomTextFieldFigmaToken0Controller:
                            
                            @classmethod
                            def hint_0_set_text(cls, text:str):
                                print("The function hint_0_set_text is unfortunately not linked to the controller")
                            
                            @classmethod
                            def text_18_set_text(cls, text:str):
                                print("The function text_18_set_text is unfortunately not linked to the controller")
                        
                        @classmethod
                        def custom_text_field_figma_token_1_set_text(cls, text:str):
                            print("The function custom_text_field_figma_token_1_set_text is unfortunately not linked to the controller")
                            return ''
                    class GroupTextFieldFigmaToken2Controller:
                        
                        @classmethod
                        def title_2_set_text(cls, text:str):
                            print("The function title_2_set_text is unfortunately not linked to the controller")
                        class CustomTextFieldFigmaToken3Controller:
                            
                            @classmethod
                            def hint_2_set_text(cls, text:str):
                                print("The function hint_2_set_text is unfortunately not linked to the controller")
                            
                            @classmethod
                            def text_20_set_text(cls, text:str):
                                print("The function text_20_set_text is unfortunately not linked to the controller")
                        
                        @classmethod
                        def custom_text_field_figma_token_4_set_text(cls, text:str):
                            print("The function custom_text_field_figma_token_4_set_text is unfortunately not linked to the controller")
                            return ''
                    class CheckboxSkipImages0Controller:
                        
                        @classmethod
                        def skip_images_0_set_text(cls, text:str):
                            print("The function skip_images_0_set_text is unfortunately not linked to the controller")
                    
                    @classmethod
                    def checkbox_skip_images_1_set_checked(cls, checked:bool) :
                        print("The function checkbox_skip_images_1_set_checked is unfortunately not linked to the controller")
                    class CustomButtonDownload0Controller:
                        class Normal7Controller:
                            
                            @classmethod
                            def text_22_set_text(cls, text:str):
                                print("The function text_22_set_text is unfortunately not linked to the controller")
                        class Disabled7Controller:
                            
                            @classmethod
                            def text_24_set_text(cls, text:str):
                                print("The function text_24_set_text is unfortunately not linked to the controller")
                        class Pressed7Controller:
                            
                            @classmethod
                            def text_26_set_text(cls, text:str):
                                print("The function text_26_set_text is unfortunately not linked to the controller")
                        class MouseOver7Controller:
                            
                            @classmethod
                            def text_28_set_text(cls, text:str):
                                print("The function text_28_set_text is unfortunately not linked to the controller")
                    
                    @classmethod
                    def custom_button_download_1_enable(cls):
                         print("The function custom_button_download_1_enable is unfortunately not linked to the controller")
                     
                    @classmethod
                    def custom_button_download_1_disable(cls):
                            print("The function custom_button_download_1_disable is unfortunately not linked to the controller")
                class CreateProject0Controller:
                    class CustomButtonCreateProject0Controller:
                        class Normal10Controller:
                            
                            @classmethod
                            def text_30_set_text(cls, text:str):
                                print("The function text_30_set_text is unfortunately not linked to the controller")
                        class Disabled10Controller:
                            
                            @classmethod
                            def text_32_set_text(cls, text:str):
                                print("The function text_32_set_text is unfortunately not linked to the controller")
                        class Pressed10Controller:
                            
                            @classmethod
                            def text_34_set_text(cls, text:str):
                                print("The function text_34_set_text is unfortunately not linked to the controller")
                        class MouseOver10Controller:
                            
                            @classmethod
                            def text_36_set_text(cls, text:str):
                                print("The function text_36_set_text is unfortunately not linked to the controller")
                    
                    @classmethod
                    def custom_button_create_project_1_enable(cls):
                         print("The function custom_button_create_project_1_enable is unfortunately not linked to the controller")
                     
                    @classmethod
                    def custom_button_create_project_1_disable(cls):
                            print("The function custom_button_create_project_1_disable is unfortunately not linked to the controller")
                    class CheckboxClearProjectDirectory0Controller:
                        
                        @classmethod
                        def clear_project_directory_0_set_text(cls, text:str):
                            print("The function clear_project_directory_0_set_text is unfortunately not linked to the controller")
                    
                    @classmethod
                    def checkbox_clear_project_directory_1_set_checked(cls, checked:bool) :
                        print("The function checkbox_clear_project_directory_1_set_checked is unfortunately not linked to the controller")
            class TabsBar0Controller:
                class Run3Controller:
                    
                    @classmethod
                    def label_8_set_text(cls, text:str):
                        print("The function label_8_set_text is unfortunately not linked to the controller")
                class Compile3Controller:
                    
                    @classmethod
                    def label_10_set_text(cls, text:str):
                        print("The function label_10_set_text is unfortunately not linked to the controller")
                class Download3Controller:
                    
                    @classmethod
                    def label_12_set_text(cls, text:str):
                        print("The function label_12_set_text is unfortunately not linked to the controller")
                class CreateProject3Controller:
                    
                    @classmethod
                    def label_14_set_text(cls, text:str):
                        print("The function label_14_set_text is unfortunately not linked to the controller")
        
        @classmethod
        def tabs_view_1_set_tab(cls, tab:int):
            print("The function tabs_view_1_set_tab is unfortunately not linked to the controller")
        class GroupTextFieldProjectDirectory0Controller:
            
            @classmethod
            def title_4_set_text(cls, text:str):
                print("The function title_4_set_text is unfortunately not linked to the controller")
            class CustomTextFieldDirectory0Controller:
                
                @classmethod
                def hint_4_set_text(cls, text:str):
                    print("The function hint_4_set_text is unfortunately not linked to the controller")
                
                @classmethod
                def text_38_set_text(cls, text:str):
                    print("The function text_38_set_text is unfortunately not linked to the controller")
            
            @classmethod
            def custom_text_field_directory_1_set_text(cls, text:str):
                print("The function custom_text_field_directory_1_set_text is unfortunately not linked to the controller")
                return ''
            class CustomButtonBrowse0Controller:
                class Normal13Controller:
                    
                    @classmethod
                    def text_40_set_text(cls, text:str):
                        print("The function text_40_set_text is unfortunately not linked to the controller")
                class Disabled13Controller:
                    
                    @classmethod
                    def text_42_set_text(cls, text:str):
                        print("The function text_42_set_text is unfortunately not linked to the controller")
                class Pressed13Controller:
                    
                    @classmethod
                    def text_44_set_text(cls, text:str):
                        print("The function text_44_set_text is unfortunately not linked to the controller")
                class MouseOver13Controller:
                    
                    @classmethod
                    def text_46_set_text(cls, text:str):
                        print("The function text_46_set_text is unfortunately not linked to the controller")
            
            @classmethod
            def custom_button_browse_1_enable(cls):
                 print("The function custom_button_browse_1_enable is unfortunately not linked to the controller")
             
            @classmethod
            def custom_button_browse_1_disable(cls):
                    print("The function custom_button_browse_1_disable is unfortunately not linked to the controller")