"""
This file was generated by PyQT figma designer
DO NOT EDIT IT. It could cause errors and it is not the way to use this program.
You can call functions from this file in your own code. 
It will allow you to change the GUI from your own code.
"""

# imports
from PySide6.QtCore import *
from PySide6.QtGui import *
from PySide6.QtWidgets import *


class ViewPyqtFigmaDesignerController:
    @classmethod
    def view_buttontext_0_set_text(cls, text:str):
        print("The function view_buttontext_0_set_text is unfortunately not linked to the controller")
        return ''
    @classmethod
    def view_buttontext_3_set_text(cls, text:str):
        print("The function view_buttontext_3_set_text is unfortunately not linked to the controller")
        return ''
    @classmethod
    def view_buttontext_6_set_text(cls, text:str):
        print("The function view_buttontext_6_set_text is unfortunately not linked to the controller")
        return ''
    @classmethod
    def view_buttontext_9_set_text(cls, text:str):
        print("The function view_buttontext_9_set_text is unfortunately not linked to the controller")
        return ''
    @classmethod
    def view_custom_button_create_project_1_enable(cls):
         print("The function view_custom_button_create_project_1_enable is unfortunately not linked to the controller")
     
    @classmethod
    def view_custom_button_create_project_1_disable(cls):
            print("The function view_custom_button_create_project_1_disable is unfortunately not linked to the controller")
    @classmethod
    def view_buttontext_12_set_text(cls, text:str):
        print("The function view_buttontext_12_set_text is unfortunately not linked to the controller")
        return ''
    @classmethod
    def view_buttontext_15_set_text(cls, text:str):
        print("The function view_buttontext_15_set_text is unfortunately not linked to the controller")
        return ''
    @classmethod
    def view_buttontext_18_set_text(cls, text:str):
        print("The function view_buttontext_18_set_text is unfortunately not linked to the controller")
        return ''
    @classmethod
    def view_buttontext_21_set_text(cls, text:str):
        print("The function view_buttontext_21_set_text is unfortunately not linked to the controller")
        return ''
    @classmethod
    def view_custom_button_browse_1_enable(cls):
         print("The function view_custom_button_browse_1_enable is unfortunately not linked to the controller")
     
    @classmethod
    def view_custom_button_browse_1_disable(cls):
            print("The function view_custom_button_browse_1_disable is unfortunately not linked to the controller")
    @classmethod
    def view_overwrite_handlers_0_set_text(cls, text:str):
        print("The function view_overwrite_handlers_0_set_text is unfortunately not linked to the controller")
        return ''
    @classmethod
    def view_progressbar_progress_1_set_progress(cls, progress:float) :
        print("Progress bar view_progressbar_progress_1 progress = " + str(progress))
    @classmethod
    def view_window_title_0_set_text(cls, text:str):
        print("The function view_window_title_0_set_text is unfortunately not linked to the controller")
        return ''
    @classmethod
    def view_slider_scale_1_set_value(cls, value:float) :
        print("Progress bar view_slider_scale_1 value = " + str(value))
    @classmethod
    def view_scale_0_set_text(cls, text:str):
        print("The function view_scale_0_set_text is unfortunately not linked to the controller")
        return ''
    @classmethod
    def view_x1_0_set_text(cls, text:str):
        print("The function view_x1_0_set_text is unfortunately not linked to the controller")
        return ''
    @classmethod
    def view_title_0_set_text(cls, text:str):
        print("The function view_title_0_set_text is unfortunately not linked to the controller")
        return ''
    @classmethod
    def view_hint_0_set_text(cls, text:str):
        print("The function view_hint_0_set_text is unfortunately not linked to the controller")
        return ''
    @classmethod
    def view_text_0_set_text(cls, text:str):
        print("The function view_text_0_set_text is unfortunately not linked to the controller")
        return ''
    @classmethod
    def view_custom_text_field_directory_1_set_text(cls, text:str):
        print("The function view_custom_text_field_directory_1_set_text is unfortunately not linked to the controller")
        return ''
    @classmethod
    def view_title_2_set_text(cls, text:str):
        print("The function view_title_2_set_text is unfortunately not linked to the controller")
        return ''
    @classmethod
    def view_hint_2_set_text(cls, text:str):
        print("The function view_hint_2_set_text is unfortunately not linked to the controller")
        return ''
    @classmethod
    def view_text_2_set_text(cls, text:str):
        print("The function view_text_2_set_text is unfortunately not linked to the controller")
        return ''
    @classmethod
    def view_custom_text_field_figma_token_1_set_text(cls, text:str):
        print("The function view_custom_text_field_figma_token_1_set_text is unfortunately not linked to the controller")
        return ''
    @classmethod
    def view_title_4_set_text(cls, text:str):
        print("The function view_title_4_set_text is unfortunately not linked to the controller")
        return ''
    @classmethod
    def view_hint_4_set_text(cls, text:str):
        print("The function view_hint_4_set_text is unfortunately not linked to the controller")
        return ''
    @classmethod
    def view_text_4_set_text(cls, text:str):
        print("The function view_text_4_set_text is unfortunately not linked to the controller")
        return ''
    @classmethod
    def view_custom_text_field_figma_token_4_set_text(cls, text:str):
        print("The function view_custom_text_field_figma_token_4_set_text is unfortunately not linked to the controller")
        return ''