"""
This file was generated by PyQT figma designer
You can edit it but be careful to not overwrite it afterwards.
Each function is connected to a specific event of a specific widget in the GUI.
"""

# imports
import model


class PyqtFigmaDesignerGuiV3Handler:

    @classmethod
    def window_started(cls):
        model.load_config()

    @classmethod
    def window_closed(cls):
        model.save_config()

    class TabsView0Handler:
        class Background0Handler:
            class GroupTextFieldProjectDirectory0Handler:

                @classmethod
                def custom_text_field_directory_1_text_changed(cls, text: str):
                    model.project_directory = text
                    model.update_ui()

                @classmethod
                def custom_button_browse_1_clicked(cls):
                    model.browse_directory()

        class TabsContent0Handler:
            class CompileOptions0Handler:

                @classmethod
                def checkbox_overwrite_handlers_1_check_changed(cls, checked: bool):
                    model.overwrite_handlers = checked

                class GroupSliderScale0Handler:

                    @classmethod
                    def slider_scale_1_value_changed(cls, value: float):
                        model.scale = model.slider_to_scale(value)
                        model.update_ui()

                @classmethod
                def custom_button_create_project_1_clicked(cls):
                    model.compile_project()

            class DownloadOptions0Handler:

                @classmethod
                def custom_button_create_project_4_clicked(cls):
                    model.download_figma_file()

                class GroupTextFieldFigmaToken0Handler:

                    @classmethod
                    def custom_text_field_figma_token_1_text_changed(cls, text: str):
                        model.figma_token = text

                class GroupTextFieldFigmaToken2Handler:

                    @classmethod
                    def custom_text_field_figma_token_4_text_changed(cls, text: str):
                        model.figma_file_url = text

    @classmethod
    def tabs_view_1_tab_changed(cls, tab: int):
        print("Tabs view tabs_view_1 tab changed to tab : " + str(tab))
