"""
This file was generated by PyQT figma designer
DO NOT EDIT IT. It could cause errors and it is not the way to use this program.
You can call functions from this file in your own code. 
It will allow you to change the GUI from your own code.
"""

# imports
from PySide6.QtCore import *
from PySide6.QtGui import *
from PySide6.QtWidgets import *


class PyqtFigmaDesignerGuiV3Controller:
    @classmethod
    def window_title_0_set_text(cls, text:str):
        print("The function window_title_0_set_text is unfortunately not linked to the controller")
    class TabsView0Controller:
        class Background0Controller:
            class TabCompile0Controller:
                
                @classmethod
                def compile_0_set_text(cls, text:str):
                    print("The function compile_0_set_text is unfortunately not linked to the controller")
            class TabDownload0Controller:
                
                @classmethod
                def compile_2_set_text(cls, text:str):
                    print("The function compile_2_set_text is unfortunately not linked to the controller")
            class GroupTextFieldProjectDirectory0Controller:
                
                @classmethod
                def title_0_set_text(cls, text:str):
                    print("The function title_0_set_text is unfortunately not linked to the controller")
                class CustomTextFieldDirectory0Controller:
                    
                    @classmethod
                    def hint_0_set_text(cls, text:str):
                        print("The function hint_0_set_text is unfortunately not linked to the controller")
                    
                    @classmethod
                    def text_0_set_text(cls, text:str):
                        print("The function text_0_set_text is unfortunately not linked to the controller")
                
                @classmethod
                def custom_text_field_directory_1_set_text(cls, text:str):
                    print("The function custom_text_field_directory_1_set_text is unfortunately not linked to the controller")
                    return ''
                class CustomButtonBrowse0Controller:
                    class Normal1Controller:
                        
                        @classmethod
                        def text_2_set_text(cls, text:str):
                            print("The function text_2_set_text is unfortunately not linked to the controller")
                    class Disabled1Controller:
                        
                        @classmethod
                        def text_4_set_text(cls, text:str):
                            print("The function text_4_set_text is unfortunately not linked to the controller")
                    class Pressed1Controller:
                        
                        @classmethod
                        def text_6_set_text(cls, text:str):
                            print("The function text_6_set_text is unfortunately not linked to the controller")
                    class MouseOver1Controller:
                        
                        @classmethod
                        def text_8_set_text(cls, text:str):
                            print("The function text_8_set_text is unfortunately not linked to the controller")
                
                @classmethod
                def custom_button_browse_1_enable(cls):
                     print("The function custom_button_browse_1_enable is unfortunately not linked to the controller")
                 
                @classmethod
                def custom_button_browse_1_disable(cls):
                        print("The function custom_button_browse_1_disable is unfortunately not linked to the controller")
        class TabsContent0Controller:
            class CompileOptions0Controller:
                class CheckboxOverwriteHandlers0Controller:
                    
                    @classmethod
                    def overwrite_handlers_0_set_text(cls, text:str):
                        print("The function overwrite_handlers_0_set_text is unfortunately not linked to the controller")
                
                @classmethod
                def checkbox_overwrite_handlers_1_set_checked(cls, checked:bool) :
                    print("The function checkbox_overwrite_handlers_1_set_checked is unfortunately not linked to the controller")
                class GroupSliderScale0Controller:
                    
                    @classmethod
                    def slider_scale_1_set_value(cls, value:float) :
                        print("The function slider_scale_1_set_value is unfortunately not linked to the controller")
                    
                    @classmethod
                    def scale_0_set_text(cls, text:str):
                        print("The function scale_0_set_text is unfortunately not linked to the controller")
                    
                    @classmethod
                    def x1_0_set_text(cls, text:str):
                        print("The function x1_0_set_text is unfortunately not linked to the controller")
                class CustomButtonCreateProject0Controller:
                    class Normal4Controller:
                        
                        @classmethod
                        def text_10_set_text(cls, text:str):
                            print("The function text_10_set_text is unfortunately not linked to the controller")
                    class Disabled4Controller:
                        
                        @classmethod
                        def text_12_set_text(cls, text:str):
                            print("The function text_12_set_text is unfortunately not linked to the controller")
                    class Pressed4Controller:
                        
                        @classmethod
                        def text_14_set_text(cls, text:str):
                            print("The function text_14_set_text is unfortunately not linked to the controller")
                    class MouseOver4Controller:
                        
                        @classmethod
                        def text_16_set_text(cls, text:str):
                            print("The function text_16_set_text is unfortunately not linked to the controller")
                
                @classmethod
                def custom_button_create_project_1_enable(cls):
                     print("The function custom_button_create_project_1_enable is unfortunately not linked to the controller")
                 
                @classmethod
                def custom_button_create_project_1_disable(cls):
                        print("The function custom_button_create_project_1_disable is unfortunately not linked to the controller")
            class DownloadOptions0Controller:
                class CustomButtonCreateProject3Controller:
                    class Normal7Controller:
                        
                        @classmethod
                        def text_18_set_text(cls, text:str):
                            print("The function text_18_set_text is unfortunately not linked to the controller")
                    class Disabled7Controller:
                        
                        @classmethod
                        def text_20_set_text(cls, text:str):
                            print("The function text_20_set_text is unfortunately not linked to the controller")
                    class Pressed7Controller:
                        
                        @classmethod
                        def text_22_set_text(cls, text:str):
                            print("The function text_22_set_text is unfortunately not linked to the controller")
                    class MouseOver7Controller:
                        
                        @classmethod
                        def text_24_set_text(cls, text:str):
                            print("The function text_24_set_text is unfortunately not linked to the controller")
                
                @classmethod
                def custom_button_create_project_4_enable(cls):
                     print("The function custom_button_create_project_4_enable is unfortunately not linked to the controller")
                 
                @classmethod
                def custom_button_create_project_4_disable(cls):
                        print("The function custom_button_create_project_4_disable is unfortunately not linked to the controller")
                class GroupTextFieldFigmaToken0Controller:
                    
                    @classmethod
                    def title_2_set_text(cls, text:str):
                        print("The function title_2_set_text is unfortunately not linked to the controller")
                    class CustomTextFieldFigmaToken0Controller:
                        
                        @classmethod
                        def hint_2_set_text(cls, text:str):
                            print("The function hint_2_set_text is unfortunately not linked to the controller")
                        
                        @classmethod
                        def text_26_set_text(cls, text:str):
                            print("The function text_26_set_text is unfortunately not linked to the controller")
                    
                    @classmethod
                    def custom_text_field_figma_token_1_set_text(cls, text:str):
                        print("The function custom_text_field_figma_token_1_set_text is unfortunately not linked to the controller")
                        return ''
                class GroupTextFieldFigmaToken2Controller:
                    
                    @classmethod
                    def title_4_set_text(cls, text:str):
                        print("The function title_4_set_text is unfortunately not linked to the controller")
                    class CustomTextFieldFigmaToken3Controller:
                        
                        @classmethod
                        def hint_4_set_text(cls, text:str):
                            print("The function hint_4_set_text is unfortunately not linked to the controller")
                        
                        @classmethod
                        def text_28_set_text(cls, text:str):
                            print("The function text_28_set_text is unfortunately not linked to the controller")
                    
                    @classmethod
                    def custom_text_field_figma_token_4_set_text(cls, text:str):
                        print("The function custom_text_field_figma_token_4_set_text is unfortunately not linked to the controller")
                        return ''
        class TabsBar2Controller:
            class Selected1Controller:
                
                @classmethod
                def download_0_set_text(cls, text:str):
                    print("The function download_0_set_text is unfortunately not linked to the controller")
            class Selected4Controller:
                
                @classmethod
                def download_2_set_text(cls, text:str):
                    print("The function download_2_set_text is unfortunately not linked to the controller")
    @classmethod
    def tabs_view_1_set_tab(cls, tab:int):
        print("The function tabs_view_1_set_tab is unfortunately not linked to the controller")