from overrides import override

from config import gui_handler_file_name, gui_controller_file_name
from generator.python_generator.base_generator import BaseGenerator
from generator.python_generator.frame_generator import FrameGenerator
from utils import indent


class ScriptGenerator(BaseGenerator):

    @override
    def generate_design(self):
        yield from f"""try:
    import {gui_handler_file_name.split('.')[0]} as GuiHandler
    import {gui_controller_file_name.split('.')[0]} as GuiController    
except Exception as e:
    print("Exception while importing gui_handler.py or controller.py")
    print(e)
from PySide6.QtSvgWidgets import QSvgWidget
from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform, QPen, QPainterPath)
from PySide6.QtWidgets import (QApplication, QFrame, QHeaderView, QLabel,
    QLineEdit, QMainWindow, QPushButton, QSizePolicy,
    QStatusBar, QTableView, QWidget)""".splitlines()
        frames = self.fig_node['children']
        for frame in frames:
            frame = FrameGenerator(frame, self.start_coordinates, self)
            yield from indent(frame.generate_design())
        if len(frames) > 0:
            yield from f"""if __name__ == '__main__':
    import sys

    app = QApplication(sys.argv)
    MainWindow = QMainWindow()
    ui = {frames[0].name}()
    ui.setupUi(MainWindow)
    MainWindow.show()
    exit_code = app.exec()
    sys.exit(exit)
""".splitlines()

    @override
    def generate_handler(self):
        yield from f"""\"\"\"
This file was generated by PyQT figma designer
You can edit it but be careful to not overwrite it afterwards.
Each function is connected to a specific event of a specific widget in the GUI.
\"\"\"

# imports
from PySide6.QtCore import *
from PySide6.QtGui import *
from PySide6.QtWidgets import *
""".splitlines()
        for frame in self.children:
            yield from frame.generate_handler()

    @override
    def generate_controller(self):
        yield from f"""\"\"\"
This file was generated by PyQT figma designer
DO NOT EDIT IT. It could cause errors and it is not the way to use this program.
You can call functions from this file in your own code. 
It will allow you to change the GUI from your own code.
\"\"\"

# imports
from PySide6.QtCore import *
from PySide6.QtGui import *
from PySide6.QtWidgets import *
""".splitlines()
        for frame in self.children:
            yield from frame.generate_controller()
